"""
handlers/admin_actions.py — Admin actions, pending requests, transactions
Mixin extracted EXACTLY from comprehensive_bot.py (verbatim, no changes).

Contains: handle_admin_actions, show_pending_requests, approve_transaction,
reject_transaction, update_transaction_status, get_transaction,
show_detailed_stats, add_company_simple, show_user_notifications_panel, etc.

DO NOT EDIT this file manually.
"""
import logging
import os
import csv
import json
from datetime import datetime


logger = logging.getLogger(__name__)


class AdminActionsMixin:

    def handle_admin_actions(self, message):
        """معالجة إجراءات الأدمن"""
        text = message['text']
        chat_id = message['chat']['id']
        user_id = message['from']['id']

        admin_user = self.find_user(user_id)
        admin_lang = admin_user.get('language', 'ar') if admin_user else 'ar'
        all_langs = self.get_supported_languages()

        # أولاً: التحقق مما إذا كان الأدمن في مرحلة إدخال سبب الرفض
        # إذا كان user_state يبدأ بـ 'awaiting_reject_reason_', فهذا يعني أننا بانتظار السبب
        user_state = self.user_states.get(user_id, '')
        # معالجة مرحلة إدخال سبب الرفض
        if isinstance(user_state, str) and user_state.startswith('awaiting_reject_reason_'):
            trans_id = user_state.replace('awaiting_reject_reason_', '')
            reason_text = text.strip()
            # إذا كتب الأدمن كلمة إلغاء أو لا يريد المتابعة
            if reason_text.lower() in [self.tr('a0011_الغاء', 'ar'), self.tr('a0010_إلغاء', 'ar'), self.tr('a0258_الغاء_العملية', 'ar'), 'cancel', self.tr('a0259_الغاء_الرفض', 'ar')]:
                # إلغاء العملية
                del self.user_states[user_id]
                # إزالة السبب المؤقت إن وجد
                if user_id in self.pending_reject_reasons:
                    del self.pending_reject_reasons[user_id]
                self.send_message(chat_id, self.tr('a0260_تم_إلغاء', 'ar', trans_id=trans_id), self.admin_keyboard())
                return
            # إذا كتب السبب
            if reason_text:
                # حفظ السبب مؤقتاً
                self.pending_reject_reasons[user_id] = {'trans_id': trans_id, 'reason': reason_text}
                # تغيير الحالة إلى تأكيد الرفض
                self.user_states[user_id] = f'confirming_reject_{trans_id}'
                # إرسال رسالة للتأكيد مع زر
                # أزرار inline لتأكيد الرفض
                inline_btns = [
                    [{'text': f'📤 تأكيد رفض', 'callback_data': f'confirm_reject_{trans_id}'},
                     {'text': '❌ إلغاء', 'callback_data': 'cancel_reject'}]
                ]
                self.send_inline_message(chat_id,
                                  self.tr('a0261_تم_حفظ', 'ar', reason_text=reason_text),
                                  inline_btns)
                return
            # إذا لم يكتب شيئاً، نعيد الطلب
            self.send_message(chat_id, self.tr('a0262_يرجى_كتابة', 'ar', trans_id=trans_id), self.admin_keyboard())
            return
        # معالجة مرحلة تأكيد الرفض
        if isinstance(user_state, str) and user_state.startswith('confirming_reject_'):
            trans_id = user_state.replace('confirming_reject_', '')
            # تأكيد الرفض
            if text.strip().startswith('📤') or self.tr('a0263_تأكيد', 'ar') in text or self.tr('a0264_تاكيد', 'ar') in text:
                pending = self.pending_reject_reasons.get(user_id)
                reason = pending['reason'] if pending else ''
                # إزالة السجلات المؤقتة
                if user_id in self.pending_reject_reasons:
                    del self.pending_reject_reasons[user_id]
                del self.user_states[user_id]
                self.reject_transaction(message, trans_id, reason)
                return
            # إلغاء الرفض خلال مرحلة التأكيد
            if text.strip().lower() in [self.tr('a0011_الغاء', 'ar'), self.tr('a0010_إلغاء', 'ar'), self.tr('a0265_إلغاء_الرفض', 'ar'), 'cancel', self.tr('a0009_إلغاء', 'ar')]:
                # إزالة السجلات المؤقتة
                if user_id in self.pending_reject_reasons:
                    del self.pending_reject_reasons[user_id]
                del self.user_states[user_id]
                self.send_message(chat_id, self.tr('a0260_تم_إلغاء', 'ar', trans_id=trans_id), self.admin_keyboard())
                return
            # أي نص آخر لا يقبل في هذه المرحلة
            self.send_message(chat_id, self.tr('a0266_يرجى_الضغط', 'ar'), self.admin_keyboard())
            return
        
        # الأزرار الرئيسية
        if text in {self.tr('admin_pending_requests', l) for l in all_langs}:
            self.show_pending_requests(message)
        elif text == self.tr('a0267_طلبات_مُوافقة', 'ar'):
            self.show_approved_transactions(message)
        elif text in {self.tr('admin_users', l) for l in all_langs}:
            self.show_users_management(message)
        elif text in {self.tr('admin_search', l) for l in all_langs}:
            self.prompt_admin_search(message)
        elif text in {self.tr('admin_managers', l) for l in all_langs}:
            self.show_admin_management(message)
        elif text in {self.tr('admin_buttons', l) for l in all_langs}:
            self.start_button_label_editor(message)
        elif text == self.tr('a0268_عرض_قائمة', 'ar'):
            self.show_detailed_admin_list(message)
        elif text == self.tr('a0269_إضافة_مدير', 'ar'):
            self.prompt_add_permanent_admin(message)
        elif text == self.tr('a0270_إضافة_مدير', 'ar'):
            self.prompt_add_temp_admin(message)
        elif text == self.tr('a0271_إزالة_مدير', 'ar'):
            self.prompt_remove_admin(message)
        elif text == self.tr('a0272_تخصيص_صلاحيات', 'ar'):
            self.start_permission_editor(message)
        elif text == self.tr('a0273_إحصائيات_المديرين', 'ar'):
            self.show_admin_statistics(message)
        elif text == self.tr('a0274_معرف_المستخدم', 'ar'):
            self.send_message(message['chat']['id'], f"🆔 معرف المستخدم الخاص بك: {message['from']['id']}", self.admin_keyboard())
        elif text in {self.tr('admin_payment_methods', l) for l in all_langs}:
            self.show_payment_methods_management(message)
        elif text == self.tr('a0275_الإحصائيات', 'ar'):
            self.show_detailed_stats(message)
        elif text in {self.tr('admin_excel_report', l) for l in all_langs}:
            self.generate_professional_excel_report(message)
        elif text in {self.tr('admin_broadcast', l) for l in all_langs}:
            self.prompt_broadcast(message)
        elif text in {self.tr('admin_ban_user', l) for l in all_langs}:
            self.prompt_ban_user(message)
        elif text in {self.tr('admin_unban_user', l) for l in all_langs}:
            self.prompt_unban_user(message)
        
        # معالجة أوامر النص المباشرة
        elif text.startswith(self.tr('a0276_الغاء_حظر', 'ar')) or text.startswith(self.tr('a0277_الغاء_حظر', 'ar')):
            customer_id = text.replace(self.tr('a0276_الغاء_حظر', 'ar'), '').replace(self.tr('a0277_الغاء_حظر', 'ar'), '').strip()
            if customer_id:
                self.unban_user_admin(message, customer_id)
            else:
                self.send_message(chat_id, self.tr('a0278_الصيغة_الصحيحة', 'ar'), self.admin_keyboard())
        elif text == self.tr('a0279_إضافة_شركة', 'ar'):
            self.start_add_company_wizard(message)
        elif text == self.tr('a0280_الشركات', 'ar'):
            self.show_companies_management_enhanced(message)
        elif text == self.tr('a0281_تحديث_القائمة', 'ar'):
            self.show_companies_management_enhanced(message)
        elif text == self.tr('a0282_إضافة_شركة', 'ar'):
            self.prompt_add_company(message)
        elif text == self.tr('a0283_تعديل_شركة', 'ar'):
            self.prompt_edit_company(message)
        elif text == self.tr('a0284_حذف_شركة', 'ar'):
            self.prompt_delete_company(message)
        elif text in [self.tr('a0285_العودة_للوحة', 'ar'), self.tr('a0286_لوحة_الأدمن', 'ar')]:
            self.handle_admin_panel(message)
        elif text in [self.tr('a0287_العودة', 'ar'), self.tr('a0142_العودة', 'ar'), self.tr('a0254_العودة', 'ar')]:
            # تحديد السياق المناسب للعودة حسب الحالة
            user_state = self.user_states.get(message['from']['id'])
            if user_state:
                if 'payment' in str(user_state) or 'method' in str(user_state):
                    self.show_payment_methods_management(message)
                elif 'company' in str(user_state):
                    self.show_companies_management_enhanced(message)
                else:
                    self.handle_admin_panel(message)
            else:
                self.handle_admin_panel(message)
        elif text in {self.tr('admin_addresses', l) for l in all_langs}:
            self.show_addresses_management(message)
        elif text in {self.tr('admin_change_language', l) for l in all_langs}:
            self.show_language_selection(message, return_to_admin=True)
        elif text == self.tr('a0288_البوتات', 'ar') and MULTI_BOT_AVAILABLE and getattr(self, 'can_manage_bots', False):
            self.show_multi_bot_panel(message)
        elif text.startswith(self.tr('a0289_اضافة_ادمن', 'ar')) and MULTI_BOT_AVAILABLE and getattr(self, 'can_manage_bots', False):
            # اضافة_ادمن_بوت BOT123 99999999
            parts = text.replace(self.tr('a0289_اضافة_ادمن', 'ar'), '').split()
            if len(parts) == 2:
                bot_id = parts[0].strip()
                admin_id = parts[1].strip()
                manager = MultiBotManager()
                if manager.add_admin(bot_id, admin_id):
                    self.send_message(message['chat']['id'],
                        self.tr('a0290_تم_إضافة', 'ar', admin_id=admin_id, bot_id=bot_id),
                        self.admin_keyboard())
                else:
                    self.send_message(message['chat']['id'], self.tr('a0291_فشل_في', 'ar'), self.admin_keyboard())
            else:
                self.send_message(message['chat']['id'],
                    self.tr('a0292_الصيغة_اضافة', 'ar'),
                    self.admin_keyboard())
        elif text.startswith(self.tr('a0293_حذف_ادمن', 'ar')) and MULTI_BOT_AVAILABLE and getattr(self, 'can_manage_bots', False):
            # حذف_ادمن_بوت BOT123 99999999
            parts = text.replace(self.tr('a0293_حذف_ادمن', 'ar'), '').split()
            if len(parts) == 2:
                bot_id = parts[0].strip()
                admin_id = parts[1].strip()
                manager = MultiBotManager()
                if manager.remove_admin(bot_id, admin_id):
                    self.send_message(message['chat']['id'],
                        self.tr('a0294_تم_حذف', 'ar', admin_id=admin_id, bot_id=bot_id),
                        self.admin_keyboard())
                else:
                    self.send_message(message['chat']['id'], self.tr('a0295_فشل_في', 'ar'), self.admin_keyboard())
            else:
                self.send_message(message['chat']['id'],
                    self.tr('a0296_الصيغة_حذف', 'ar'),
                    self.admin_keyboard())
        elif text in {self.tr('admin_themes', l) for l in all_langs} and THEME_AVAILABLE:
            self.show_theme_panel(message)
        elif text.startswith(self.tr('a0297_ثيم', 'ar')) and THEME_AVAILABLE:
            theme_key = text.replace(self.tr('a0297_ثيم', 'ar'), '').strip()
            self.save_setting('active_theme', theme_key)
            theme = get_theme(theme_key)
            self.send_message(message['chat']['id'],
                f"✅ تم تفعيل ثيم: {theme.get('icon', '')} {theme.get('name_ar', theme_key)}\n\n"
                f"سيتم تطبيق الثيم على جميع الرسائل والأزرار.",
                self.admin_keyboard())
            return
        elif text in {self.tr('admin_support_data', l) for l in all_langs}:
            self.show_support_data_editor(message)
        elif text in {self.tr('admin_settings', l) for l in all_langs}:
            self.show_system_settings(message)
        elif text in {self.tr('admin_complaints', l) for l in all_langs}:
            self.show_complaints_admin(message)
        elif text in [self.tr('a0298_تحديث_الشكاوى', 'ar'), self.tr('a0299_تحديث', 'ar')]:
            self.show_complaints_admin(message)
        elif text.startswith(self.tr('a0300_رد_على', 'ar')):
            complaint_id = text.replace(self.tr('a0300_رد_على', 'ar'), '').strip()
            self.start_complaint_reply_wizard(message, complaint_id)
        elif text in {self.tr('admin_quick_commands', l) for l in all_langs}:
            self.show_quick_copy_commands(message)
        elif text in {self.tr('admin_recovery', l) for l in all_langs} and self.svrp:
            self.show_svrp_admin_panel(message)
        elif text in {self.tr('admin_apps', l) for l in all_langs}:
            self.show_apps_admin_panel(message)
        elif text == self.tr('a0301_تداول', 'ar'):
            self.show_trade_admin_queue(message)
        elif text == self.tr('a0302_كل_الطلبات', 'ar'):
            self.show_unified_orders(message)
        elif text == self.tr('a0303_روابط_الإحالة', 'ar'):
            self.show_referral_links_admin(message)
        elif text == self.tr('a0304_القنوات', 'ar'):
            self.show_channels_admin(message)
        elif text == self.tr('a0305_مكتبة_الرموز', 'ar'):
            self.show_sticker_library(message)
        elif text == self.tr('a0306_المطابقات', 'ar'):
            self.show_match_admin_panel(message)
        elif text == self.tr('a0307_أرباح_الإحالة', 'ar'):
            self.show_referral_earnings_admin(message)
        elif text == self.tr('a0308_اليانصيب', 'ar'):
            self.show_lottery_admin(message)
        elif text == self.tr('a0236_عجلة_الحظ', 'ar'):
            self.show_wheel_admin(message)
        elif text in {self.tr('admin_message_user', l) for l in all_langs}:
            self.start_send_user_message(message)
        elif text in {self.tr('admin_notifications', l) for l in all_langs}:
            self.show_notifications_panel(message)
        elif text in {self.tr('admin_backup', l) for l in all_langs}:
            self.manual_backup_command(message)
        elif text == self.tr('a0309_إضافة_وسيلة', 'ar'):
            self.start_simple_payment_method_wizard(message)
        elif text == self.tr('a0310_تعديل_وسيلة', 'ar'):
            self.start_edit_payment_method_wizard(message)
        elif text == self.tr('a0311_حذف_وسيلة', 'ar'):
            self.start_delete_payment_method_wizard(message)
        elif text == self.tr('a0312_عرض_وسائل', 'ar'):
            self.show_all_payment_methods_simplified(message)
        elif text == self.tr('a0313_إيقاف_وسيلة', 'ar'):
            self.start_disable_payment_method_wizard(message)
        elif text == self.tr('a0314_تشغيل_وسيلة', 'ar'):
            self.start_enable_payment_method_wizard(message)
        elif text in {self.tr('admin_main_menu', l) for l in all_langs}:
            # إنهاء جلسة الأدمن والعودة للقائمة الرئيسية
            if message['from']['id'] in self.user_states:
                del self.user_states[message['from']['id']]
            user = self.find_user(message['from']['id'])
            if user:
                # استخدام الترجمة لعرض شاشة اختيار الخدمة كاملة بلغته
                lang = user.get('language', 'ar')
            else:
                lang = admin_lang
                welcome_text = self.tr(
                    'choose_service',
                    lang,
                    name=user.get('name', self.tr('a0122_غير_محدد', lang)) if user else '',
                    customer_id=user.get('customer_id', self.tr('a0122_غير_محدد', lang)) if user else ''
                )
                self.send_message(chat_id, welcome_text, self.main_keyboard(lang))
        
        # أوامر نصية للأدمن (مبسطة مع احتمالات متعددة)
        elif any(word in text.lower() for word in [self.tr('a0315_موافقة', admin_lang), self.tr('a0316_موافق', admin_lang), self.tr('a0317_اوافق', admin_lang), self.tr('a0318_أوافق', admin_lang), self.tr('a0319_قبول', admin_lang), self.tr('a0320_مقبول', admin_lang), self.tr('a0263_تأكيد', admin_lang), self.tr('a0264_تاكيد', admin_lang), self.tr('a0198_نعم', admin_lang)]):
            # استخراج رقم المعاملة
            words = text.split()
            trans_id = None
            for word in words:
                if any(word.startswith(prefix) for prefix in ['DEP', 'WTH']):
                    trans_id = word
                    break
            
            if trans_id:
                self.approve_transaction(message, trans_id)
            else:
                self.send_message(message['chat']['id'], self.tr('a0321_لم_يتم', lang), self.admin_keyboard())
                
        elif any(word in text.lower() for word in [self.tr('a0322_رفض', lang), self.tr('a0323_رافض', lang), 'لا', self.tr('a0324_مرفوض', lang), self.tr('a0010_إلغاء', lang), self.tr('a0011_الغاء', lang), self.tr('a0325_منع', lang)]):
            # استخراج رقم المعاملة والسبب
            words = text.split()
            trans_id = None
            reason_start = -1
            for i, word in enumerate(words):
                if any(word.startswith(prefix) for prefix in ['DEP', 'WTH']):
                    trans_id = word
                    reason_start = i + 1
                    break
            if trans_id:
                # تجميع بقية الكلمات كسبب
                reason = ' '.join(words[reason_start:]) if reason_start != -1 and reason_start < len(words) else ''
                # إذا لم يتم تقديم سبب، نطلب من الأدمن كتابته
                if not reason.strip():
                    # تعيين حالة انتظار السبب لهذا الأدمن
                    self.user_states[user_id] = f'awaiting_reject_reason_{trans_id}'
                    self.send_message(chat_id, self.tr('a0326_يرجى_كتابة', lang, trans_id=trans_id), self.admin_keyboard())
                    return
                # إذا تم تقديم السبب، نقوم برفض المعاملة مباشرة
                self.reject_transaction(message, trans_id, reason)
            else:
                self.send_message(message['chat']['id'], self.tr('a0327_لم_يتم', lang), self.admin_keyboard())
        elif text.startswith(self.tr('a0328_بحث', lang)):
            query = text.replace(self.tr('a0328_بحث', lang), '')
            self.search_users_admin(message, query)
        elif text.startswith(self.tr('a0329_اضافة_ادمن', lang)):
            user_id_to_add = text.replace(self.tr('a0329_اضافة_ادمن', lang), '')
            self.add_admin_user(message, user_id_to_add)
        elif text.startswith(self.tr('a0330_اضافة_ادمن', lang)):
            user_id_to_add = text.replace(self.tr('a0330_اضافة_ادمن', lang), '')
            self.add_admin_user(message, user_id_to_add)
        elif text.startswith(self.tr('a0331_ادمن_مؤقت', lang)):
            parts = text.replace(self.tr('a0331_ادمن_مؤقت', lang), '').split()
            if len(parts) < 1:
                self.send_message(chat_id, self.tr('a0332_الصيغة_ادمن', lang), self.admin_keyboard())
                return
            user_id_to_add = parts[0]
            role = parts[1] if len(parts) > 1 else 'full'
            try:
                duration = int(parts[2]) if len(parts) > 2 else 0
            except ValueError:
                duration = 0
            self.add_temp_admin(message, user_id_to_add, role=role, duration_hours=duration)
        elif text.startswith(self.tr('a0333_صلاحيات', lang)):
            parts = text.replace(self.tr('a0333_صلاحيات', lang), '').split()
            if len(parts) >= 2:
                admin_id_str = parts[0]
                role = parts[1]
                self.set_admin_role(message, admin_id_str, role)
            else:
                self.send_message(chat_id, self.tr('a0334_الصيغة_صلاحيات', lang), self.admin_keyboard())
        elif text.startswith(self.tr('a0335_ازالة_ادمن', lang)):
            user_id_to_remove = text.replace(self.tr('a0335_ازالة_ادمن', lang), '')
            self.remove_admin_user(message, user_id_to_remove)
        elif text.startswith(self.tr('a0336_حظر', lang)):
            parts = text.replace(self.tr('a0336_حظر', 'ar'), '').split(' ', 1)
            customer_id = parts[0]
            reason = parts[1] if len(parts) > 1 else self.tr('a0337_مخالفة_الشروط', 'ar')
            self.ban_user_admin(message, customer_id, reason)
        elif text.startswith(self.tr('a0276_الغاء_حظر', 'ar')):
            customer_id = text.replace(self.tr('a0276_الغاء_حظر', 'ar'), '')
            self.unban_user_admin(message, customer_id)
        elif text.startswith(self.tr('a0338_اضافة_شركة', 'ar')):
            self.add_company_simple_with_display(message, text)
        elif text.startswith(self.tr('a0339_حذف_شركة', 'ar')):
            company_id = text.replace(self.tr('a0339_حذف_شركة', 'ar'), '')
            self.delete_company_simple(message, company_id)
        elif text.startswith(self.tr('a0340_عنوان_جديد', 'ar')):
            new_address = text.replace(self.tr('a0340_عنوان_جديد', 'ar'), '')
            self.update_address_simple(message, new_address)
        elif any(word in text.lower() for word in [self.tr('a0341_عنوان', 'ar'), self.tr('a0342_العنوان', 'ar'), self.tr('a0343_تحديث_عنوان', 'ar')]):
            # استخراج العنوان الجديد
            new_address = text
            for word in [self.tr('a0341_عنوان', 'ar'), self.tr('a0342_العنوان', 'ar'), self.tr('a0343_تحديث_عنوان', 'ar')]:
                new_address = new_address.replace(word, '').strip()
            if new_address:
                self.update_address_simple(message, new_address)
            else:
                self.send_message(message['chat']['id'], self.tr('a0344_يرجى_كتابة', 'ar'), self.admin_keyboard())
        elif text.startswith(self.tr('a0345_تعديل_اعداد', 'ar')):
            self.update_setting_simple(message, text)
        elif text.startswith(self.tr('a0346_تعديل_استرداد', 'ar')) and self.svrp:
            # تعديل إعدادات تعويض 100%
            parts = text.replace(self.tr('a0346_تعديل_استرداد', 'ar'), '').split()
            if len(parts) == 2:
                key = parts[0].strip()
                try:
                    val = parts[1].strip()
                    old_val = self.svrp._get_config(key)
                    if old_val != 0 or key in ['recovery_multiplier', 'max_recovery_cap', 'credit_expiry_days',
                                               'wagering_requirement', 'promo_code_max_uses',
                                               'promo_code_expiry_days', 'max_recovery_per_month']:
                        # تحديث القيمة في SVRP_CONFIG
                        from svrp import SVRP_CONFIG
                        if isinstance(SVRP_CONFIG.get(key), float):
                            SVRP_CONFIG[key] = float(val)
                        elif isinstance(SVRP_CONFIG.get(key), int):
                            SVRP_CONFIG[key] = int(val)
                        else:
                            SVRP_CONFIG[key] = val
                        self.send_message(message['chat']['id'],
                            self.tr('a0347_تم_تحديث', 'ar', key=key, old_val=old_val, val=val),
                            self.admin_keyboard())
                    else:
                        self.send_message(message['chat']['id'],
                            self.tr('a0348_مفتاح_غير', 'ar', key=key), self.admin_keyboard())
                except ValueError:
                    self.send_message(message['chat']['id'],
                        self.tr('a0349_قيمة_غير', 'ar'), self.admin_keyboard())
            else:
                self.send_message(message['chat']['id'],
                    self.tr('a0350_الصيغة_تعديل', 'ar'),
                    self.admin_keyboard())
        elif text == self.tr('a0351_حفظ_الشركة', 'ar'):
            # التعامل مع حفظ الشركة - تنفيذ مباشر
            if user_id in self.user_states and self.user_states[user_id] == 'confirming_company':
                if user_id in self.temp_company_data:
                    company_data = self.temp_company_data[user_id]
                    company_id = str(int(datetime.now().timestamp()))
                    
                    try:
                        # حفظ الشركة في الملف مع الأيقونة والعنوان
                        icon = company_data.get('icon', '🏢')
                        address = company_data.get('address', '')
                        affiliate = company_data.get('affiliate_link', '')
                        with open('companies.csv', 'a', newline='', encoding='utf-8-sig') as f:
                            writer = csv.writer(f)
                            writer.writerow([company_id, company_data['name'], company_data['type'], company_data['details'], 'active', icon, address, affiliate])
                        
                        success_msg = self.tr('a0352_تم_إضافة', 'ar', company_id=company_id, company_data_name=company_data['name'], company_data_type_display=company_data['type_display'], company_data_details=company_data['details'])
                        
                        self.send_message(chat_id, success_msg, self.admin_keyboard())
                        
                        # تنظيف البيانات المؤقتة
                        del self.user_states[user_id]
                        del self.temp_company_data[user_id]
                        
                    except Exception as e:
                        self.send_message(chat_id, f"❌ فشل في حفظ الشركة: {str(e)}", self.admin_keyboard())
                else:
                    self.send_message(chat_id, self.tr('a0353_لا_توجد', 'ar'), self.admin_keyboard())
            else:
                self.send_message(chat_id, self.tr('a0354_لا_توجد', 'ar'), self.admin_keyboard())
        elif text == self.tr('a0355_حفظ_التغييرات', 'ar'):
            # التعامل مع حفظ تغييرات الشركة
            if user_id in self.user_states and self.user_states[user_id] == 'editing_company_menu':
                self.save_company_changes(message)
            else:
                self.send_message(chat_id, self.tr('a0356_لا_توجد', 'ar'), self.admin_keyboard())
        elif text in [self.tr('a0009_إلغاء', 'ar'), self.tr('a0010_إلغاء', 'ar'), self.tr('a0011_الغاء', 'ar')]:
            # إلغاء العملية الحالية
            if user_id in self.user_states:
                del self.user_states[user_id]
            if user_id in self.edit_company_data:
                del self.edit_company_data[user_id]
            self.send_message(chat_id, self.tr('a0357_تم_إلغاء', 'ar'), self.admin_keyboard())
        else:
            self.send_message(message['chat']['id'], self.tr('a0358_أمر_غير', 'ar'), self.main_keyboard('ar', user_id))
    
    def show_pending_requests(self, message):
        """عرض الطلبات المعلقة للأدمن — تشمل pending و pending_code_verification"""
        pending_text = self.tr('a0359_الطلبات_المعلقة', 'ar')
        found_pending = False
        copy_commands = []
        
        try:
            with open('transactions.csv', 'r', encoding='utf-8-sig') as f:
                reader = csv.DictReader(f)
                for row in reader:
                    if row['status'] in ('pending', 'pending_code_verification'):
                        found_pending = True
                        type_emoji = "💰" if row['type'] == 'deposit' else "💸"
                        status_tag = "⏳" if row['status'] == 'pending' else "🔐"
                        
                        pending_text += f"{type_emoji} {status_tag} {row['id']}\n"
                        pending_text += f"👤 {row['name']} ({row['customer_id']})\n"
                        pending_text += f"🏢 {row['company']}\n"
                        pending_text += f"💳 {row['wallet_number']}\n"
                        pending_text += f"{self.fmt_amount(row['amount'], row.get('type', 'deposit'))}\n"
                        
                        if row.get('exchange_address'):
                            pending_text += f"📍 {row['exchange_address']}\n"
                        
                        if row.get('admin_note') and row['status'] == 'pending_code_verification':
                            pending_text += self.tr('a0360_الكود', 'ar', row_admin_note=row['admin_note'])
                        
                        pending_text += f"📅 {row['date']}\n"
                        
                        # إضافة أوامر النسخ السريع
                        pending_text += self.tr('a0361_أوامر_سريعة', 'ar')
                        pending_text += self.tr('a0362_موافقة', 'ar', row_id=row['id'])
                        pending_text += self.tr('a0363_رفض_السبب', 'ar', row_id=row['id'])
                        pending_text += f"▫️▫️▫️▫️▫️▫️▫️▫️▫️▫️\n\n"
                        
                        copy_commands.append({
                            'id': row['id'],
                            'approve': f"موافقة {row['id']}",
                            'reject': f"رفض {row['id']} السبب_هنا"
                        })
        except:
            pass
        
        if not found_pending:
            pending_text += self.tr('a0364_لا_توجد', 'ar')
        else:
            # إضافة قسم الأوامر الجاهزة للنسخ
            pending_text += self.tr('a0365_أوامر_جاهزة', 'ar')
            
            for cmd in copy_commands:
                pending_text += f"**{cmd['id']}:**\n"
                pending_text += f"✅ `{cmd['approve']}`\n"
                pending_text += f"❌ `{cmd['reject']}`\n\n"
            
            pending_text += self.tr('a0366_طرق_سهلة', 'ar')
            pending_text += self.tr('a0367_انقر_على', 'ar')
            pending_text += self.tr('a0368_أو_اكتب', 'ar')
            pending_text += self.tr('a0369_للرفض_رفض', 'ar')
            
            pending_text += self.tr('a0370_أمثلة_أوامر', 'ar')
            pending_text += self.tr('a0371_موافقة_أو', 'ar')
            
            pending_text += self.tr('a0372_أمثلة_أوامر', 'ar')
            pending_text += self.tr('a0373_رفض_أو', 'ar')
        
        self.send_message(message['chat']['id'], pending_text, self.admin_keyboard())
    
    def approve_transaction(self, message, trans_id):
        """الموافقة على معاملة"""
        success = self.update_transaction_status(trans_id, 'approved', '', str(message['from']['id']))
        
        if success:
            # إشعار العميل الذكي
            transaction = self.get_transaction(trans_id)
            if transaction:
                customer_telegram_id = transaction.get('telegram_id')
                if customer_telegram_id:
                    user = self.find_user(customer_telegram_id)
                    lang = user.get('language', 'ar') if user else 'ar'
                    customer_msg = self.tr('transaction_approved', lang, trans_id=trans_id)
                    nav_btns = [[{'text': '🏠 القائمة الرئيسية', 'callback_data': 'main_menu'}]]
                    self.notify_user(int(customer_telegram_id), customer_msg, 'transaction_approved', nav_btns)
                    
                    # 💎 تعويض 100%: تحديث المهام + تفعيل أرصدة الأصدقاء + زيادة الرهان
                    if self.svrp:
                        try:
                            amount = float(transaction.get('amount', 0) or 0)
                            trans_type = transaction.get('type', '')
                            if trans_type == 'deposit':
                                self.svrp.update_task_progress(customer_telegram_id, 'deposit_count', 1)
                                self.svrp.update_task_progress(customer_telegram_id, 'deposit_amount', amount)
                                # تفعيل أرصدة الأصدقاء (إذا كان هذا المستخدم مُحالاً)
                                self.svrp.activate_friend_credits(customer_telegram_id)
                            # زيادة عداد الرهان
                            self.svrp.increment_wagering(customer_telegram_id)
                            # تحديث مجموعة المستخدم
                            self.svrp.update_user_group(customer_telegram_id)
                        except Exception as e:
                            logger.error(f"خطأ في تحديث تعويض 100%: {e}")
            
            self.send_message(message['chat']['id'], self.tr('transaction_approved', 'ar', trans_id=trans_id), self.admin_keyboard())
        else:
            self.send_message(message['chat']['id'], f"❌ {trans_id}", self.admin_keyboard())
    
    def reject_transaction(self, message, trans_id, reason):
        """رفض معاملة"""
        success = self.update_transaction_status(trans_id, 'rejected', reason, str(message['from']['id']))
        
        if success:
            # إشعار العميل
            transaction = self.get_transaction(trans_id)
            if transaction:
                customer_telegram_id = transaction.get('telegram_id')
                if customer_telegram_id:
                    user = self.find_user(customer_telegram_id)
                    lang = user.get('language', 'ar') if user else 'ar'
                    customer_msg = self.tr('transaction_rejected', lang, trans_id=trans_id, reason=reason)
                    nav_btns = [[{'text': '🏠 القائمة الرئيسية', 'callback_data': 'main_menu'}]]
                    self.notify_user(int(customer_telegram_id), customer_msg, 'transaction_rejected', nav_btns)
                    
                    # 💎 تعويض 100%: تشغيل الاسترداد عند رفض السحب
                    if self.svrp and transaction.get('type') == 'withdraw':
                        try:
                            amount = float(transaction.get('amount', 0) or 0)
                            if amount > 0:
                                result, err = self.svrp.trigger_recovery(
                                    customer_telegram_id, trans_id, amount,
                                    transaction.get('currency', 'SAR')
                                )
                                if result:
                                    credit_str = f"{result['total_credit']:.2f} {result['currency']}"
                                    svrp_msg = (
                                        f"{self.tr('svrp_recovery_activated', lang)}\n\n"
                                        f"{self.fmt_success(self.tr('svrp_recovery_credit', lang) + ': ' + credit_str)}\n"
                                        f"📥 {self.tr('svrp_recovery_keep', lang)}: {result['keep_amount']:.2f}\n"
                                        f"📤 {self.tr('svrp_recovery_share', lang)}: {result['share_amount']:.2f}\n\n"
                                        f"📋 {self.tr('svrp_recovery_requirements', lang)}:\n"
                                        f"• {self.tr('svrp_recovery_complete_tx', lang, n=result['wagering_required'])}\n"
                                        f"• {self.tr('svrp_recovery_expires', lang)}: {result['expires_at']}\n\n"
                                        f"{self.tr('svrp_recovery_share_hint', lang)}"
                                    )
                                    nav_btns = [[{'text': '💎 لوحة التعويض', 'callback_data': 'svrp_back_panel'}]]
                                    self.notify_user(int(customer_telegram_id), svrp_msg, 'svrp_recovery', nav_btns)
                        except Exception as e:
                            logger.error(f"خطأ في تشغيل تعويض 100%: {e}")
            
            self.send_message(message['chat']['id'], self.tr('transaction_rejected', 'ar', trans_id=trans_id, reason=reason), self.admin_keyboard())
        else:
            self.send_message(message['chat']['id'], f"❌ {trans_id}", self.admin_keyboard())
    
    def update_transaction_status(self, trans_id, new_status, note='', admin_id=''):
        """تحديث حالة المعاملة"""
        transactions = []
        success = False
        
        try:
            with open('transactions.csv', 'r', encoding='utf-8-sig') as f:
                reader = csv.DictReader(f)
                for row in reader:
                    if row['id'] == trans_id:
                        row['status'] = new_status
                        if note:
                            row['admin_note'] = note
                        if admin_id:
                            row['processed_by'] = admin_id
                        success = True
                    transactions.append(row)
            
            if success:
                with open('transactions.csv', 'w', newline='', encoding='utf-8-sig') as f:
                    fieldnames = [
                        'id',
                        'customer_id',
                        'telegram_id',
                        'name',
                        'type',
                        'company',
                        'wallet_number',
                        'amount',
                        'exchange_address',
                        'status',
                        'date',
                        'admin_note',
                        'processed_by',
                        'currency'
                    ]
                    writer = csv.DictWriter(f, fieldnames=fieldnames)
                    writer.writeheader()
                    writer.writerows(transactions)

        except:
            pass
        
        # ── Smart Engine: Fire webhook + chain event for transaction status change ──
        if success and getattr(self, 'smart_engine', None):
            try:
                # Find the transaction to get user info
                trans = None
                for t in transactions:
                    if t['id'] == trans_id:
                        trans = t
                        break
                if trans:
                    event_type = f"transaction_{new_status}"
                    extra = {
                        'trans_id': trans_id,
                        'type': trans.get('type', ''),
                        'amount': trans.get('amount', ''),
                        'user_id': trans.get('telegram_id', ''),
                        'status': new_status,
                    }
                    self.smart_engine.fire_event(event_type, trans.get('telegram_id', ''), extra)
                    self.smart_engine.trigger_webhook(event_type, extra)
            except Exception:
                pass
        
        return success
    
    def get_transaction(self, trans_id):
        """جلب معاملة محددة"""
        try:
            with open('transactions.csv', 'r', encoding='utf-8-sig') as f:
                reader = csv.DictReader(f)
                for row in reader:
                    if row['id'] == trans_id:
                        return row
        except:
            pass
        return None
    
    def show_detailed_stats(self, message):
        """عرض إحصائيات مفصلة"""
        stats_text = self.tr('a0374_إحصائيات_النظام', 'ar')
        
        # إحصائيات المستخدمين
        total_users = 0
        banned_users = 0
        try:
            with open('users.csv', 'r', encoding='utf-8-sig') as f:
                reader = csv.DictReader(f)
                for row in reader:
                    total_users += 1
                    if row.get('is_banned') == 'yes':
                        banned_users += 1
        except:
            pass
        
        # إحصائيات المعاملات
        total_transactions = 0
        pending_count = 0
        code_verification_count = 0
        approved_count = 0
        rejected_count = 0
        total_deposit_amount = 0
        total_withdraw_amount = 0
        
        try:
            with open('transactions.csv', 'r', encoding='utf-8-sig') as f:
                reader = csv.DictReader(f)
                for row in reader:
                    total_transactions += 1
                    amount = float(row.get('amount', 0) or 0)
                    
                    if row['status'] == 'pending':
                        pending_count += 1
                    elif row['status'] == 'pending_code_verification':
                        code_verification_count += 1
                    elif row['status'] == 'approved':
                        approved_count += 1
                        if row['type'] == 'deposit':
                            total_deposit_amount += amount
                        else:
                            total_withdraw_amount += amount
                    elif row['status'] == 'rejected':
                        rejected_count += 1
        except:
            pass
        
        # إحصائيات الشكاوى
        total_complaints = 0
        try:
            with open('complaints.csv', 'r', encoding='utf-8-sig') as f:
                reader = csv.DictReader(f)
                total_complaints = sum(1 for row in reader)
        except:
            pass
        
        stats_text += self.tr('a0375_المستخدمون', 'ar')
        stats_text += self.tr('a0376_الإجمالي', 'ar', total_users=total_users)
        stats_text += f"├ النشطون: {total_users - banned_users}\n"
        stats_text += self.tr('a0377_المحظورون', 'ar', banned_users=banned_users)
        
        stats_text += self.tr('a0378_المعاملات', 'ar')
        stats_text += self.tr('a0379_الإجمالي', 'ar', total_transactions=total_transactions)
        stats_text += self.tr('a0380_معلقة', 'ar', pending_count=pending_count)
        stats_text += self.tr('a0381_بانتظار_تأكيد', 'ar', code_verification_count=code_verification_count)
        stats_text += self.tr('a0382_مُوافق_عليها', 'ar', approved_count=approved_count)
        stats_text += self.tr('a0383_مرفوضة', 'ar', rejected_count=rejected_count)
        
        stats_text += self.tr('a0384_المبالغ_المُوافق', 'ar')
        stats_text += self.tr('a0385_الإيداعات', 'ar', total_deposit_amount=total_deposit_amount)
        stats_text += self.tr('a0386_السحوبات', 'ar', total_withdraw_amount=total_withdraw_amount)
        stats_text += f"└ الفرق: {total_deposit_amount - total_withdraw_amount:,.0f}\n\n"
        
        stats_text += self.tr('a0387_الشكاوى', 'ar', total_complaints=total_complaints)
        stats_text += f"📅 {datetime.now().strftime('%Y-%m-%d %H:%M')}"
        
        self.send_message(message['chat']['id'], stats_text, self.admin_keyboard())
    
    def add_company_simple_with_display(self, message, text):
        """إضافة شركة مع عرض القائمة المحدثة"""
        result = self.add_company_simple(message, text)
        if result:
            # عرض قائمة الشركات المحدثة فوراً
            self.show_companies_management_enhanced(message)
    
    def add_company_simple(self, message, text):
        """إضافة شركة بصيغة مبسطة"""
        # تنسيق: اضافة_شركة اسم نوع تفاصيل
        parts = text.replace(self.tr('a0338_اضافة_شركة', 'ar'), '').split(' ', 2)
        if len(parts) < 3:
            help_text = self.tr('a0388_طريقة_إضافة', 'ar')
            
            self.send_message(message['chat']['id'], help_text, self.admin_keyboard())
            return
        
        company_name = parts[0].replace('_', ' ')
        service_type = parts[1].lower()
        details = parts[2].replace('_', ' ')
        
        # قبول الكلمات العربية وتحويلها
        if service_type in [self.tr('a0389_ايداع', 'ar'), self.tr('a0390_إيداع', 'ar')]:
            service_type = 'deposit'
        elif service_type in [self.tr('a0391_سحب', 'ar')]:
            service_type = 'withdraw'
        elif service_type in [self.tr('a0392_كلاهما', 'ar'), self.tr('a0171_الكل', 'ar'), self.tr('a0393_ايداع_وسحب', 'ar')]:
            service_type = 'both'
        
        if service_type not in ['deposit', 'withdraw', 'both']:
            error_text = self.tr('a0394_نوع_الخدمة', 'ar')
            
            self.send_message(message['chat']['id'], error_text, self.admin_keyboard())
            return
        
        # إنشاء معرف جديد
        company_id = str(int(datetime.now().timestamp()))
        
        try:
            # التأكد من وجود الملف وإنشاؤه إذا لم يكن موجوداً
            file_exists = True
            try:
                with open('companies.csv', 'r', encoding='utf-8-sig') as f:
                    pass
            except FileNotFoundError:
                file_exists = False
            
            # إنشاء الملف مع الرؤوس إذا لم يكن موجوداً
            if not file_exists:
                with open('companies.csv', 'w', newline='', encoding='utf-8-sig') as f:
                    writer = csv.writer(f)
                    writer.writerow(['id', 'name', 'type', 'details', 'is_active'])
            
            # إضافة الشركة الجديدة
            with open('companies.csv', 'a', newline='', encoding='utf-8-sig') as f:
                writer = csv.writer(f)
                company_icon = self.normalize_icon(service_type, default='🏢')
                writer.writerow([company_id, company_name, service_type, details, 'active', company_icon, ''])
            
            # رسالة النجاح مع عرض قائمة الشركات المحدثة
            success_msg = self.tr('a0395_تم_إضافة', 'ar', company_id=company_id, company_icon=company_icon, company_name=company_name, service_type=service_type, details=details)
            
            # عرض جميع الشركات
            try:
                with open('companies.csv', 'r', encoding='utf-8-sig') as f:
                    reader = csv.DictReader(f)
                    company_count = 0
                    for row in reader:
                        company_count += 1
                        status = "✅" if row.get('is_active') == 'active' else "❌"
                        type_display = {'deposit': 'إيداع', 'withdraw': 'سحب', 'both': 'الكل'}.get(row['type'], row['type'])
                        success_msg += f"\n{status} {row['name']} (ID: {row['id']}) - {type_display}"
                    
                    success_msg += self.tr('a0396_إجمالي_الشركات', 'ar', company_count=company_count)
            except:
                pass
            
            self.send_message(message['chat']['id'], success_msg, self.admin_keyboard())
            return True
            
        except Exception as e:
            self.send_message(message['chat']['id'], f"❌ فشل في إضافة الشركة: {str(e)}", self.admin_keyboard())
            return False
    
    def update_address_simple(self, message, new_address):
        """تحديث عنوان الصرافة"""
        try:
            with open('exchange_addresses.csv', 'w', newline='', encoding='utf-8-sig') as f:
                writer = csv.writer(f)
                writer.writerow(['id', 'address', 'is_active'])
                writer.writerow(['1', new_address, 'yes'])
            
            self.send_message(message['chat']['id'], self.tr('a0397_تم_تحديث', 'ar', new_address=new_address), self.admin_keyboard())
        except Exception as e:
            self.send_message(message['chat']['id'], f"❌ فشل في تحديث العنوان: {str(e)}", self.admin_keyboard())
    
    # ==================== نظام المطابقة ====================

    def show_user_notifications_panel(self, message):
        """عرض إشعارات المستخدم"""
        user_id = message['from']['id']
        user = self.find_user(user_id)
        if not user:
            return
        lang = user.get('language', 'ar')
        
        notifs = self.get_user_notifications(user_id, 10)
        
        if not notifs:
            self.send_message(message['chat']['id'], self.tr('notif_empty', lang), self.main_keyboard(lang, user_id))
            return
        
        type_icons = {
            'new_deposit': '💰', 'new_withdraw': '💸', 'new_complaint': '📨',
            'new_match': '🔄', 'dispute': '⚖️', 'code_verification': '🔐',
            'transaction_approved': '✅', 'transaction_rejected': '❌',
            'code_verified': '✅', 'code_rejected': '❌', 'general': '📋'
        }
        
        notif_text = f"{self.tr('notif_recent', lang)}\n\n"
        for n in reversed(notifs):
            icon = type_icons.get(n.get('type', ''), '📋')
            notif_text += f"{icon} {n.get('timestamp', '')}\n{n.get('message_preview', '')}\n\n"
        
        self.send_message(message['chat']['id'], notif_text, self.main_keyboard(lang, user_id))

    def start_matching_flow(self, message):
        """بدء تدفق المطابقة — شرح + قواعد + موافقة"""
        user = self.find_user(message['from']['id'])
        if not user:
            return
        lang = user.get('language', 'ar')

        # فحص وجود طلب مطابقة معلق (waiting) — حذف القديم وعرضه
        if self.match_manager:
            # فحص طلبات waiting القديمة
            waiting_req = self.match_manager.get_active_request_by_user(str(message['from']['id']))
            if waiting_req:
                # حذف الطلب القديم المعلق
                try:
                    rows = []
                    with open('match_requests.csv', 'r', encoding='utf-8-sig') as f:
                        reader = csv.DictReader(f)
                        fieldnames = reader.fieldnames
                        for row in reader:
                            if not (row.get('id') == waiting_req.get('id') and row.get('status') == 'waiting'):
                                rows.append(row)
                    with open('match_requests.csv', 'w', newline='', encoding='utf-8-sig') as f:
                        writer = csv.DictWriter(f, fieldnames=fieldnames)
                        writer.writeheader()
                        writer.writerows(rows)
                    logger.info(f"Cleaned old waiting request: {waiting_req.get('id')}")
                except:
                    pass

        # فحص وجود مطابقة نشطة — عرضها إن وجدت
        if self.match_manager:
            active_match = self.match_manager.get_match_by_user(message['from']['id'])
            if active_match:
                # عرض المطابقة النشطة مع تفاصيلها
                match = active_match
                match_status = match.get('status', 'active')
                status_ar = {
                    'active': '🟢 نشطة',
                    'awaiting_code': '🔐 بانتظار الكود',
                    'code_verified': '✅ تم تأكيد الكود',
                    'awaiting_payment': '💸 بانتظار التحويل',
                    'awaiting_admin_review': '⏳ بانتظار مراجعة الإدارة',
                    'admin_received': '✅ الإدارة استلمت المال',
                    'transfer_confirmed': '✅ تم تأكيد التحويل',
                    'completed': '✅ مكتملة',
                    'disputed': '⚖️ نزاع مفتوح',
                    'cancelled': '❌ ملغاة'
                }.get(match_status, match_status)

                text = (
                    f"⚠️ <b>لديك مطابقة نشطة</b>\n\n"
                    f"━━━━━━━━━━━━━━━━━━\n"
                    f"🆔 المطابقة: <code>{match['id']}</code> 👈 اضغط للنسخ\n"
                    f"📊 الحالة: <b>{status_ar}</b>\n"
                    f"💰 المبلغ: <code>{match.get('amount', '')}</code> {match.get('currency', '')}\n"
                    f"🏢 الشركة: <b>{match.get('company_name', '')}</b>\n"
                    f"━━━━━━━━━━━━━━━━━━\n\n"
                )

                # عرض الأزرار المناسبة حسب الحالة
                inline_btns = []
                if match_status in ('active', 'awaiting_code'):
                    # الساحب: عليه إرسال الكود
                    if str(match.get('withdrawer_id', '')) == str(message['from']['id']):
                        text += self.tr('a0398_عليك_إرسال', lang)
                        inline_btns.append([{'text': '📝 إرسال الكود', 'callback_data': f'match_enter_code_btn_{match["id"]}'}])
                    # المودع: بانتظار الساحب
                    elif str(match.get('depositor_id', '')) == str(message['from']['id']):
                        text += self.tr('a0399_بانتظار_قيام', lang)

                if match_status == 'code_verified':
                    if str(match.get('depositor_id', '')) == str(message['from']['id']):
                        text += self.tr('a0400_حوّل_المال', lang)
                        inline_btns.append([{'text': '✅ تم الإرسال', 'callback_data': f'match_sent_{match["id"]}'}])
                        inline_btns.append([{'text': '❌ إلغاء', 'callback_data': f'match_cancel_warn_{match["id"]}'}])
                    elif str(match.get('withdrawer_id', '')) == str(message['from']['id']):
                        text += self.tr('a0401_بانتظار_قيام', lang)

                if match_status in ('awaiting_admin_review', 'admin_received', 'transfer_confirmed'):
                    text += self.tr('a0402_بانتظار_مراجعة', lang)

                if match_status == 'transfer_confirmed' and str(match.get('depositor_id', '')) == str(message['from']['id']):
                    text += self.tr('a0403_تأكد_من', lang)
                    inline_btns.append([{'text': '✅ تأكيد الاستلام', 'callback_data': f'match_confirm_received_{match["id"]}'}])
                    inline_btns.append([{'text': '❌ لم يصل', 'callback_data': f'match_not_received_{match["id"]}'}])

                if match_status in ('active', 'awaiting_code') and str(match.get('depositor_id', '')) == str(message['from']['id']):
                    if not any('cancel' in b.get('callback_data', '') for row in inline_btns for b in row):
                        inline_btns.append([{'text': '❌ إلغاء', 'callback_data': f'match_cancel_warn_{match["id"]}'}])

                inline_btns.append([{'text': '🆘 دعم', 'callback_data': f'match_support_{match["id"]}'}])
                inline_btns.append([{'text': '🔙 القائمة الرئيسية', 'callback_data': 'match_back_main'}])

                self.send_inline_message(message['chat']['id'], text, inline_btns)
                return

        # لا توجد مطابقة نشطة — عرض شروط المطابقة + بدء
        if lang == 'ar':
            text = (
                "🔄 <b>نظام المطابقة P2P</b>\n\n"
                "━━━━━━━━━━━━━━━━━━\n"
                "📌 <b>كيف يعمل النظام؟</b>\n"
                "━━━━━━━━━━━━━━━━━━\n"
                "1️⃣ اختر نوع العملية (إيداع أو سحب)\n"
                "2️⃣ حدد الشركة ووسيلة الدفع\n"
                "3️⃣ أدخل بياناتك خطوة بخطوة\n"
                "4️⃣ الإدارة تراجع وتؤكد طلبك\n"
                "5️⃣ بعد تأكيد الإدارة ← تتابع العملية\n"
                "6️⃣ حوّل المال ← أرسل لقطة شاشة\n"
                "7️⃣ الإدارة تؤكد الاستلام ← تحوّل لك ← تؤكد الاستلام\n\n"
                "⚠️ <b>تحذيرات:</b>\n"
                "• 🚫 <b>لا ترسل المال قبل أن يؤكد لك ذلك</b>\n"
                "• ✅ بياناتك محفوظة بأمان ولن تُفقد\n"
                "• التقييم إلزامي بعد كل عملية\n"
                "• في حالة نزاع → اضغط <b>🆘 دعم</b>\n"
                "━━━━━━━━━━━━━━━━━━\n\n"
                "هل توافق على القواعد؟"
            )
        else:
            text = (
                "🔄 <b>P2P Matching System</b>\n\n"
                "━━━━━━━━━━━━━━━━━━\n"
                "📌 <b>How it works:</b>\n"
                "1️⃣ Choose operation type (deposit or withdraw)\n"
                "2️⃣ Select company and payment method\n"
                "3️⃣ Enter your data step by step\n"
                "4️⃣ Admin reviews and confirms your request\n"
                "5️⃣ After admin approval ← proceed\n"
                "6️⃣ Send money ← send screenshot\n"
                "7️⃣ Admin confirms receipt ← sends to you ← you confirm\n\n"
                "⚠️ <b>Warnings:</b>\n"
                "• 🚫 <b>Do NOT send money before confirmed by admin</b>\n"
                "• ✅ Your data is safely stored\n"
                "• Rating is mandatory after each operation\n"
                "• In case of dispute → press <b>🆘 Support</b>\n"
                "━━━━━━━━━━━━━━━━━━\n\n"
                "Do you agree to the rules?"
            )

        inline_btns = [
            [{'text': '✅ موافقة', 'callback_data': 'match_agree'},
             {'text': '🔙 العودة', 'callback_data': 'match_cancel'}]
        ]
        self.send_inline_message(message['chat']['id'], text, inline_btns)

    def handle_matching_flow(self, message):
        """معالجة تدفق المطابقة — كل الخطوات في مكان واحد"""
        user_id = message['from']['id']
        chat_id = message['chat']['id']
        state = self.user_states.get(user_id, '')
        text = message.get('text', '').strip()
        user = self.find_user(user_id)
        if not user:
            return
        lang = user.get('language', 'ar')

        # === match_enter_data: المبلغ ← المحفظة ← المعرف ===
        if isinstance(state, dict) and state.get('step') == 'match_enter_data':
            text_msg = message.get('text', '').strip()

            if text_msg in [self.tr('a0009_إلغاء', lang), self.tr('a0010_إلغاء', lang), self.tr('a0011_الغاء', lang), '🔙', self.tr('a0083_القائمة_الرئيسية', lang)]:
                del self.user_states[user_id]
                self.handle_start(message)
                return

            substep = state.get('substep', 'amount')

            if substep == 'amount':
                try:
                    amount = float(text_msg)
                    if amount <= 0:
                        self.send_message(chat_id, self.tr('a0144_المبلغ_يجب', lang))
                        return
                except ValueError:
                    self.send_message(chat_id, self.tr('a0145_اكتب_مبلغاً', lang))
                    return
                state['amount'] = str(amount)
                state['substep'] = 'wallet'
                self.user_states[user_id] = state
                kb = {'keyboard': [[{'text': '❌ إلغاء'}]], 'resize_keyboard': True, 'one_time_keyboard': True}
                self.send_message(chat_id,
                    f"✅ المبلغ: <code>{amount}</code>\n"
                    f"🔒 <b>بياناتك محفوظة بأمان</b>\n\n"
                    f"2️⃣ اكتب <b>رقم محفظتك</b>:\n\n"
                    f"⚠️ <b>لا ترسل المال قبل أن يؤكد لك ذلك</b>", kb)
                return

            if substep == 'wallet':
                wallet_number = self.sanitize_input(text_msg)
                if len(wallet_number) < 5:
                    self.send_message(chat_id, self.tr('a0146_رقم_المحفظة', lang))
                    return
                state['wallet_number'] = wallet_number
                state['substep'] = 'account'
                self.user_states[user_id] = state
                kb = {'keyboard': [[{'text': '❌ إلغاء'}]], 'resize_keyboard': True, 'one_time_keyboard': True}
                self.send_message(chat_id,
                    f"✅ المحفظة: <code>{wallet_number}</code> 👈 اضغط للنسخ\n"
                    f"🔒 <b>بياناتك محفوظة بأمان</b>\n\n"
                    f"3️⃣ اكتب <b>معرف حسابك</b> (ID):\n\n"
                    f"⚠️ <b>لا ترسل المال قبل أن يؤكد لك ذلك</b>", kb)
                return

            if substep == 'account':
                account_id = self.sanitize_input(text_msg)
                if len(account_id) < 2:
                    self.send_message(chat_id, self.tr('a0404_معرف_الحساب', lang))
                    return

                # ✅ تأكيد حفظ البيانات
                self.send_message(chat_id,
                    f"✅ معرف الحساب: <code>{account_id}</code> 👈 اضغط للنسخ\n"
                    f"🔒 <b>جميع بياناتك محفوظة بأمان</b>\n\n"
                    f"⏳ جارٍ إنشاء طلبك ومراجعته من الإدارة...\n\n"
                    f"⚠️ <b>لا ترسل المال قبل أن يؤكد لك ذلك</b>")

                amount = state.get('amount', '0')
                wallet_number = state.get('wallet_number', '')
                match_type = state.get('type', 'deposit')
                company_id = state.get('company_id', '')
                company_name = state.get('company_name', '')

                # إنشاء طلب المطابقة
                try:
                    req_id, error = self.match_manager.create_match_request(
                        str(user_id), user.get('customer_id', ''), match_type,
                        str(amount), user.get('currency', 'SAR'),
                        str(company_id), company_name, ''
                    )
                    if error:
                        self.send_message(chat_id, f"❌ {error}", self.main_keyboard(lang, user_id))
                        del self.user_states[user_id]
                        return
                except Exception as e:
                    logger.error(f"خطأ في create_match_request: {e}")
                    self.send_message(chat_id,
                        self.tr('a0405_حدث_خطأ', 'ar'),
                        self.main_keyboard(lang, user_id))
                    del self.user_states[user_id]
                    return

                # البحث عن مطابقة
                request = None
                match = None
                try:
                    request = self.match_manager.get_active_request_by_user(str(user_id))
                    if request:
                        match = self.match_manager.find_match(request)
                except Exception as e:
                    logger.error(f"خطأ في find_match: {e}")

                if request and match:
                    try:
                        match_id = self.match_manager.create_match(request, match)
                        self._notify_match_created(match_id)
                        del self.user_states[user_id]
                        return
                    except Exception as e:
                        logger.error(f"خطأ في create_match: {e}")

                # لا توجد مطابقة — العميل ينتظر موافقة الإدارة + الأدمن يصبح الطرف الآخر تلقائياً
                type_ar = self.tr('a0390_إيداع', 'ar') if match_type == 'deposit' else self.tr('a0391_سحب', 'ar')
                nav_btns = [[{'text': '🔄 المطابقة', 'callback_data': 'match_back_main'},
                             {'text': '🏠 القائمة', 'callback_data': 'main_menu'}]]
                self.send_inline_message(chat_id,
                    f"⏳ <b>تم إنشاء طلبك بنجاح!</b>\n\n"
                    f"━━━━━━━━━━━━━━━━━━\n"
                    f"{'💵' if match_type == 'deposit' else '💸'} النوع: <b>{type_ar}</b>\n"
                    f"💰 المبلغ: <code>{amount}</code>\n"
                    f"🏢 الشركة: <b>{company_name}</b>\n"
                    f"💳 المحفظة: <code>{wallet_number}</code> 👈 اضغط للنسخ\n"
                    f"🆔 معرف الحساب: <code>{account_id}</code> 👈 اضغط للنسخ\n"
                    f"━━━━━━━━━━━━━━━━━━\n\n"
                    f"🔒 <b>بياناتك محفوظة بأمان</b>\n"
                    f"⏳ بانتظار موافقة الإدارة على طلبك\n\n"
                    f"⚠️ <b>لا ترسل المال قبل أن يؤكد لك ذلك</b>", nav_btns)

                # الأدمن يصبح الطرف الآخر تلقائياً + يرى كل البيانات + يوافق/يرفض
                if request:
                    for admin_id in self.admin_ids:
                        try:
                            opposite_type = self.tr('a0391_سحب', 'ar') if match_type == 'deposit' else self.tr('a0390_إيداع', 'ar')
                            self.send_inline_message(int(admin_id),
                                f"🔔 <b>طلب مطابقة جديد</b>\n\n"
                                f"━━━━━━━━━━━━━━━━━━\n"
                                f"👤 العميل: <code>{user_id}</code> ({user.get('name', '')})\n"
                                f"{'💵' if match_type == 'deposit' else '💸'} النوع: <b>{type_ar}</b>\n"
                                f"🔄 سيكون الطرف الآخر: <b>{opposite_type}</b>\n"
                                f"💰 المبلغ: <code>{amount}</code>\n"
                                f"🏢 الشركة: <b>{company_name}</b>\n"
                                f"💳 المحفظة: <code>{wallet_number}</code> 👈 اضغط للنسخ\n"
                                f"🆔 معرف الحساب: <code>{account_id}</code> 👈 اضغط للنسخ\n"
                                f"━━━━━━━━━━━━━━━━━━\n\n"
                                f"✅ اضغط موافقة لتأكيد الطلب للعميل\n"
                                f"❌ أو رفض لإلغاء الطلب",
                                [[{'text': '✅ موافقة', 'callback_data': f'match_admin_approve_req_{request["id"]}'},
                                  {'text': '❌ رفض', 'callback_data': f'match_admin_reject_req_{request["id"]}'}]])
                        except Exception as e:
                            logger.error(f"خطأ في إشعار الأدمن: {e}")

                del self.user_states[user_id]
                return

        # معالجة قديمة — اختيار النوع (يُترك للتوافق الخلفي)
        if state == 'match_select_type':
            if text == self.tr('a0406_مطابقة_إيداع', 'ar'):
                match_type = 'deposit'
            elif text == self.tr('a0407_مطابقة_سحب', 'ar'):
                match_type = 'withdraw'
            else:
                return

            # حفظ النوع وطلب المبلغ
            self.user_states[user_id] = {'step': 'match_amount', 'type': match_type}
            self.send_message(message['chat']['id'], self.tr('a0408_أدخل_المبلغ', 'ar'))
            return

        # إدخال المبلغ
        if isinstance(state, dict) and state.get('step') == 'match_amount':
            amount = self.validate_amount(text)
            if amount is None:
                self.send_message(message['chat']['id'], self.tr('a0409_مبلغ_غير', 'ar'))
                return

            state['amount'] = amount
            state['step'] = 'match_company'

            # عرض الشركات
            companies = self.get_companies('both')
            if not companies:
                self.send_message(message['chat']['id'], self.tr('a0410_لا_توجد', 'ar'))
                return

            keyboard = []
            for c in companies:
                icon = self.display_icon(c.get('icon'), '🏢')
                keyboard.append([{'text': f"{icon} {c['name']}"}])
            keyboard.append([{'text': self.tr('main_menu', lang)}])

            self.send_message(message['chat']['id'], self.tr('a0411_اختر_الشركة', 'ar'),
                {'keyboard': keyboard, 'resize_keyboard': True, 'one_time_keyboard': True})
            self.user_states[user_id] = state
            return

        # اختيار الشركة
        if isinstance(state, dict) and state.get('step') == 'match_company':
            company_name = text
            for emoji in ['🏢', '🏦', '📡', '📱', '💳', '👛', '💵', '🔄', '🏷️', '⭐', '🚀', '🏬', '🌐', '🥇', '🎁']:
                if company_name.startswith(emoji):
                    company_name = company_name[len(emoji):].strip()
                    break

            companies = self.get_companies('both')
            selected = None
            for c in companies:
                if c['name'] == company_name:
                    selected = c
                    break

            if not selected:
                self.send_message(message['chat']['id'], self.tr('a0412_شركة_غير', 'ar'))
                return

            state['company_id'] = selected['id']
            state['company_name'] = selected['name']
            state['payment_method_id'] = ''

            # إنشاء طلب المطابقة
            req_id, error = self.match_manager.create_match_request(
                user_id, user['customer_id'], state['type'],
                state['amount'], user.get('currency', 'SAR'),
                selected['id'], selected['name'], '')

            if error:
                self.send_message(message['chat']['id'], f"❌ {error}", self.main_keyboard(lang, user_id))
                del self.user_states[user_id]
                return

            # البحث عن مطابقة
            request = self.match_manager.get_active_request_by_user(user_id)
            if request:
                match = self.match_manager.find_match(request)
                if match:
                    # مطابقة موجودة!
                    match_id = self.match_manager.create_match(request, match)
                    self._notify_match_created(match_id)
                    del self.user_states[user_id]
                    return

            # لا توجد مطابقة — إشعار الأدمن + إبلاغ العميل
            req_type_ar = self.tr('a0390_إيداع', 'ar') if state['type'] == 'deposit' else self.tr('a0391_سحب', 'ar')
            self.send_message(message['chat']['id'],
                f"⏳ <b>تم إنشاء طلبك</b>\n\n"
                f"━━━━━━━━━━━━━━━━━━\n"
                f"{'💵' if state['type'] == 'deposit' else '💸'} النوع: <b>{req_type_ar}</b>\n"
                f"💰 المبلغ: <b>{state['amount']}</b>\n"
                f"🏢 الشركة: <b>{selected['name']}</b>\n"
                f"━━━━━━━━━━━━━━━━━━\n\n"
                f"⏳ جارٍ البحث عن مطابقة...\n"
                f"سيتم إشعارك فور العثور على طرف آخر.",
                self.main_keyboard(lang, user_id))

            # إشعار جميع الأدمن بطلب المطابقة المعلق
            for admin_id in self.admin_ids:
                try:
                    opposite_type = self.tr('a0391_سحب', 'ar') if state['type'] == 'deposit' else self.tr('a0390_إيداع', 'ar')
                    admin_msg = (
                        f"🔔 <b>طلب مطابقة معلق</b>\n\n"
                        f"━━━━━━━━━━━━━━━━━━\n"
                        f"👤 العميل: <code>{user_id}</code> ({user.get('name', '')})\n"
                        f"{'💵' if state['type'] == 'deposit' else '💸'} النوع: <b>{req_type_ar}</b>\n"
                        f"🔄 يبحث عن: <b>{opposite_type}</b>\n"
                        f"💰 المبلغ: <b>{state['amount']}</b>\n"
                        f"🏢 الشركة: <b>{selected['name']}</b>\n"
                        f"━━━━━━━━━━━━━━━━━━\n\n"
                        f"يمكنك أن تكون الطرف الآخر في هذه المطابقة:"
                    )
                    inline_btns = [
                        [{'text': f'✅ أنا الطرف الآخر ({opposite_type})', 'callback_data': f'match_admin_join_{request["id"]}'},
                         {'text': '⏳ انتظار', 'callback_data': f'match_admin_wait_{request["id"]}'}]
                    ]
                    self.send_inline_message(admin_id, admin_msg, inline_btns)
                except Exception as e:
                    logger.error(f"خطأ في إشعار الأدمن بطلب المطابقة: {e}")

            del self.user_states[user_id]
            return

        # إدخال كود السحب + البيانات — خطوة بخطوة
        if isinstance(state, dict) and state.get('step') == 'match_enter_code':
            state['substep'] = state.get('substep', 'code')

            if text in [self.tr('a0009_إلغاء', 'ar'), self.tr('a0010_إلغاء', 'ar'), self.tr('a0011_الغاء', 'ar'), '🔙']:
                if user_id in self.user_states: del self.user_states[user_id]
                self.handle_start(message)
                return

            if state['substep'] == 'code':
                code = self.sanitize_input(text)
                if len(code) < 3:
                    self.send_message(message['chat']['id'], self.tr('a0413_الكود_قصير', 'ar'))
                    return
                state['code'] = code
                state['substep'] = 'account'
                kb = {'keyboard': [[{'text': '❌ إلغاء'}]], 'resize_keyboard': True, 'one_time_keyboard': True}
                self.send_message(message['chat']['id'],
                    f"✅ الكود: <code>{code}</code> 👈 اضغط للنسخ\n\n"
                    f"2️⃣ اكتب <b>معرف حسابك</b> (ID):", kb)
                self.user_states[user_id] = state
                return

            if state['substep'] == 'account':
                account_id = self.sanitize_input(text)
                if len(account_id) < 2:
                    self.send_message(message['chat']['id'], self.tr('a0404_معرف_الحساب', 'ar'))
                    return
                state['account_id'] = account_id
                state['substep'] = 'wallet'
                kb = {'keyboard': [[{'text': '❌ إلغاء'}]], 'resize_keyboard': True, 'one_time_keyboard': True}
                self.send_message(message['chat']['id'],
                    f"✅ معرف الحساب: <code>{account_id}</code> 👈 اضغط للنسخ\n\n"
                    f"3️⃣ اكتب <b>رقم محفظتك</b>:", kb)
                self.user_states[user_id] = state
                return

            if state['substep'] == 'wallet':
                wallet_number = self.sanitize_input(text)
                if len(wallet_number) < 5:
                    self.send_message(message['chat']['id'], self.tr('a0414_رقم_المحفظة', 'ar'))
                    return
                state['wallet_number'] = wallet_number
                state['substep'] = 'method'
                kb = {'keyboard': [[{'text': '❌ إلغاء'}]], 'resize_keyboard': True, 'one_time_keyboard': True}
                self.send_message(message['chat']['id'],
                    f"✅ المحفظة: <code>{wallet_number}</code> 👈 اضغط للنسخ\n\n"
                    f"4️⃣ اكتب <b>وسيلة الدفع</b>:", kb)
                self.user_states[user_id] = state
                return

            if state['substep'] == 'method':
                payment_method_name = self.sanitize_input(text)
                if len(payment_method_name) < 2:
                    self.send_message(message['chat']['id'], self.tr('a0415_وسيلة_الدفع', 'ar'))
                    return

                for emoji in ['💳', '🏦', '📱', '👛', '💵', '📡', '🏷️']:
                    if payment_method_name.startswith(emoji):
                        payment_method_name = payment_method_name[len(emoji):].strip()
                        break

                match_id = state['match_id']
                code = state['code']
                account_id = state['account_id']
                wallet_number = state['wallet_number']

                combined_code = f"{code} | ID:{account_id} | Wallet:{wallet_number} | Method:{payment_method_name}"
                self.match_manager.set_confirmation_code(match_id, combined_code)

                match = self.match_manager.get_match_by_id(match_id)
                for admin_id in self.admin_ids:
                    try:
                        admin_msg = (
                            f"🔐 <b>طلب سحب — مطابقة</b>\n\n"
                            f"🆔 رقم المطابقة: <code>{match_id}</code> 👈 اضغط للنسخ\n"
                            f"💰 المبلغ: <code>{match['amount']}</code> {match['currency']}\n"
                            f"🏢 الشركة: <b>{match['company_name']}</b>\n\n"
                            f"🔑 الكود: <code>{code}</code> 👈 اضغط للنسخ\n"
                            f"🆔 معرف الحساب: <code>{account_id}</code> 👈 اضغط للنسخ\n"
                            f"💳 المحفظة: <code>{wallet_number}</code> 👈 اضغط للنسخ\n"
                            f"📋 الوسيلة: <b>{payment_method_name}</b>\n"
                        )
                        inline_btns = [
                            [{'text': '✅ تأكيد الكود', 'callback_data': f'match_verify_{match_id}'},
                             {'text': '❌ رفض الكود', 'callback_data': f'match_reject_code_{match_id}'}]
                        ]
                        self.send_inline_message(admin_id, admin_msg, inline_btns)
                    except:
                        pass

                self.send_message(message['chat']['id'],
                    f"✅ <b>تم إرسال بياناتك للتحقق</b>\n\n"
                    f"🔑 الكود: <code>{code}</code> 👈 اضغط للنسخ\n"
                    f"🆔 معرف الحساب: <code>{account_id}</code> 👈 اضغط للنسخ\n"
                    f"💳 المحفظة: <code>{wallet_number}</code> 👈 اضغط للنسخ\n"
                    f"📋 الوسيلة: <b>{payment_method_name}</b>\n\n"
                    f"⏳ سيتم إشعارك فور التأكيد",
                    self.main_keyboard(lang, user_id))
                del self.user_states[user_id]
                return

        # رفع لقطة شاشة (تحويل مال)
        if isinstance(state, dict) and state.get('step') == 'match_upload_screenshot':
            match_id = state.get('match_id', '')
            role = state.get('role', '')
            match = self.match_manager.get_match_by_id(match_id)
            if not match:
                self.send_message(chat_id, self.tr('a0416_المطابقة_غير', 'ar'), self.main_keyboard(lang, user_id))
                del self.user_states[user_id]
                return

            # قبول صورة أو مستند
            photo = message.get('photo', [])
            document = message.get('document', {})

            if not photo and not document:
                self.send_message(chat_id,
                    "📸 <b>أرسل لقطة شاشة التحويل</b>\n\n"
                    f"🆔 <code>{match_id}</code> 👈 اضغط للنسخ\n"
                    f"📤 أرسل صورة أو مستند إثبات التحويل\n\n"
                    f"🔒 <b>بياناتك محفوظة بأمان</b>")
                return

            # الحصول على file_id
            if photo:
                file_id = photo[-1]['file_id']  # أعلى جودة
            else:
                file_id = document.get('file_id', '')

            if not file_id:
                self.send_message(chat_id, self.tr('a0417_تعذّر_استلام', 'ar'))
                return

            if role == 'admin':
                # الأدمن رفع لقطة شاشة تحويله للعميل → إرسال للمودع لتأكيد الاستلام
                dep_id = int(match['depositor_id'])
                dep_user = self.find_user(dep_id)
                dep_lang = dep_user.get('language', 'ar') if dep_user else 'ar'

                caption = (
                    f"📸 <b>لقطة شاشة تحويل — من الإدارة</b>\n\n"
                    f"━━━━━━━━━━━━━━━━━━\n"
                    f"🆔 المطابقة: <code>{match_id}</code> 👈 اضغط للنسخ\n"
                    f"💰 المبلغ: <code>{match.get('amount', '')}</code> {match.get('currency', '')}\n"
                    f"🏢 الشركة: <b>{match.get('company_name', '')}</b>\n"
                    f"━━━━━━━━━━━━━━━━━━\n\n"
                    f"✅ تأكد من وصول المال ثم اضغط تأكيد الاستلام\n\n"
                    f"🔒 <b>بياناتك محفوظة بأمان</b>"
                )
                # إرسال الصورة للمودع
                url = f"{self.api_url}sendPhoto"
                payload = {'chat_id': dep_id, 'photo': file_id, 'caption': caption, 'parse_mode': 'HTML'}
                try:
                    import requests
                    requests.post(url, json=payload, timeout=10)
                except:
                    pass

                # إرسال أزرار inline بعد الصورة
                inline_btns = [
                    [{'text': '✅ تأكيد الاستلام', 'callback_data': f'match_confirm_received_{match_id}'}],
                    [{'text': '❌ لم يصل', 'callback_data': f'match_not_received_{match_id}'}]
                ]
                self.send_inline_message(dep_id, self.tr('a0418_هل_وصل', 'ar'), inline_btns)

                self.send_message(chat_id,
                    f"✅ <b>تم إرسال لقطة الشاشة للعميل</b>\n\n"
                    f"🆔 <code>{match_id}</code>\n"
                    f"⏳ بانتظار تأكيد العميل للاستلام",
                    self.admin_keyboard())
            else:
                # العميل رفع لقطة شاشة تحويله → إرسال للأدمن للمراجعة
                for admin_id in self.admin_ids:
                    try:
                        caption = (
                            f"📸 <b>لقطة شاشة تحويل — مطابقة</b>\n\n"
                            f"━━━━━━━━━━━━━━━━━━\n"
                            f"🆔 المطابقة: <code>{match_id}</code> 👈 اضغط للنسخ\n"
                            f"💰 المبلغ: <code>{match.get('amount', '')}</code> {match.get('currency', '')}\n"
                            f"🏢 الشركة: <b>{match.get('company_name', '')}</b>\n"
                            f"👤 المرسل: <code>{user_id}</code> ({role})\n"
                            f"━━━━━━━━━━━━━━━━━━"
                        )
                        # إرسال الصورة للأدمن
                        url = f"{self.api_url}sendPhoto"
                        payload = {'chat_id': int(admin_id), 'photo': file_id, 'caption': caption, 'parse_mode': 'HTML'}
                        try:
                            import requests
                            requests.post(url, json=payload, timeout=10)
                        except:
                            pass

                        # إرسال أزرار inline بعد الصورة
                        inline_btns = [
                            [{'text': '✅ تأكيد التحويل', 'callback_data': f'match_admin_screenshot_ok_{match_id}'},
                             {'text': '❌ رفض', 'callback_data': f'match_admin_screenshot_no_{match_id}'}]
                        ]
                        self.send_inline_message(int(admin_id), self.tr('a0419_مراجعة_لقطة', 'ar'), inline_btns)
                    except Exception as e:
                        logger.error(f"خطأ في إرسال لقطة الشاشة للأدمن: {e}")

                self.send_message(chat_id,
                    f"✅ <b>تم إرسال لقطة الشاشة للإدارة</b>\n\n"
                    f"🆔 <code>{match_id}</code> 👈 اضغط للنسخ\n"
                    f"⏳ بانتظار مراجعة الإدارة\n\n"
                    f"🔒 <b>بياناتك محفوظة بأمان</b>",
                    self.main_keyboard(lang, user_id))

            del self.user_states[user_id]
            return

        # دردشة
        if isinstance(state, dict) and state.get('step') == 'chatting':
            match_id = state['match_id']
            result = self.match_manager.send_chat_message(match_id, user_id, text)
            if result:
                # توجيه الرسالة للطرف الآخر
                other_lang = 'ar'  # افتراضي
                other_user = self.find_user(result['receiver_id'])
                if other_user:
                    other_lang = other_user.get('language', 'ar')

                chat_keyboard = {
                    'keyboard': [
                        [{'text': '🆘 دعم'}, {'text': '✅ تأكيد'}],
                        [{'text': self.tr('main_menu', other_lang)}]
                    ],
                    'resize_keyboard': True
                }
                self.send_message(result['receiver_id'],
                    f"💬 {result['sender_alias']}:\n{text}", chat_keyboard)
            return

        # تقييم
        if isinstance(state, dict) and state.get('step') == 'rating':
            try:
                rating = int(text)
                if rating < 1 or rating > 5:
                    raise ValueError()
            except (ValueError, TypeError):
                self.send_message(message['chat']['id'], self.tr('a0420_أدخل_رقم', 'ar'))
                return

            self.match_manager.rate_user(state['match_id'], user_id, rating)
            self.send_message(message['chat']['id'], self.tr('a0421_شكراً_لتقييمك', 'ar'), self.main_keyboard(lang, user_id))
            del self.user_states[user_id]
            return

    def _notify_match_created(self, match_id):
        """إشعار الطرفين بإنشاء مطابقة — الساحب يرسل الكود، المودع ينتظر"""
        match = self.match_manager.get_match_by_id(match_id)
        if not match:
            return

        depositor_id = int(match['depositor_id'])
        withdrawer_id = int(match['withdrawer_id'])

        # إشعار المودع: بانتظار الساحب
        dep_user = self.find_user(depositor_id)
        dep_lang = dep_user.get('language', 'ar') if dep_user else 'ar'
        dep_msg = (
            f"✅ <b>تم تأكيد طلبك وإنشاء المطابقة!</b>\n\n"
            f"━━━━━━━━━━━━━━━━━━\n"
            f"🆔 <code>{match_id}</code> 👈 اضغط للنسخ\n"
            f"💰 المبلغ: <code>{match['amount']}</code> {match['currency']}\n"
            f"🏢 الشركة: <b>{match['company_name']}</b>\n"
            f"━━━━━━━━━━━━━━━━━━\n\n"
            f"⏳ بانتظار قيام الطرف الآخر بإرسال بيانات السحب\n\n"
            f"⚠️ <b>لا ترسل المال قبل أن يؤكد لك ذلك</b>\n"
            f"🔒 <b>بياناتك محفوظة بأمان</b>"
        )
        self.send_message(depositor_id, dep_msg, self.main_keyboard(dep_lang, depositor_id))

        # إشعار الساحب: أرسل بياناتك (كود + معرف + محفظة + وسيلة)
        wit_user = self.find_user(withdrawer_id)
        wit_lang = wit_user.get('language', 'ar') if wit_user else 'ar'
        wit_msg = (
            f"✅ <b>تم تأكيد طلبك وإنشاء المطابقة!</b>\n\n"
            f"━━━━━━━━━━━━━━━━━━\n"
            f"🆔 <code>{match_id}</code> 👈 اضغط للنسخ\n"
            f"💰 المبلغ: <code>{match['amount']}</code> {match['currency']}\n"
            f"🏢 الشركة: <b>{match['company_name']}</b>\n"
            f"━━━━━━━━━━━━━━━━━━\n\n"
            f"📝 <b>أرسل بياناتك الآن:</b>\n"
            f"1️⃣ كود السحب\n"
            f"2️⃣ معرف حسابك (ID)\n"
            f"3️⃣ رقم محفظتك\n"
            f"4️⃣ وسيلة الدفع\n\n"
            f"⚠️ <b>لا ترسل المال قبل أن يؤكد لك ذلك</b>\n"
            f"🔒 <b>بياناتك محفوظة بأمان</b>"
        )
        kb = {'keyboard': [[{'text': '❌ إلغاء'}]], 'resize_keyboard': True, 'one_time_keyboard': True}
        self.send_message(withdrawer_id, wit_msg, kb)
        self.user_states[withdrawer_id] = {'step': 'match_enter_code', 'match_id': match_id, 'substep': 'code'}

        # إشعار الإدمن
        for admin_id in self.admin_ids:
            try:
                admin_msg = (
                    f"🔗 مطابقة جديدة\n\n"
                    f"🆔 {match_id}\n"
                    f"💰 {match['amount']} {match['currency']}\n"
                    f"🏢 {match['company_name']}\n"
                    f"👤 المودع: {match['depositor_alias']}\n"
                    f"👤 الساحب: {match['withdrawer_alias']}"
                )
                self.send_message(admin_id, admin_msg, self.admin_keyboard())
            except:
                pass

